/** Erros de domínio com código estável (mapeados para HTTP na API). */
export type ErrorCode =
  | 'ILLEGAL_TRANSITION' | 'DEAL_NOT_FOUND' | 'DEAL_EXPIRED' | 'DEAL_TERMINAL' | 'INVALID_INPUT' | 'NOT_PARTICIPANT'
  | 'ASSET_NOT_CANONICAL' | 'ASSET_VERIFICATION_FAILED' | 'PRICE_UNAVAILABLE' | 'PRICE_ANOMALY' | 'LIQUIDITY_INSUFFICIENT' | 'LIQUIDITY_UNAVAILABLE'
  | 'ROUTE_NOT_VIABLE' | 'ROUTE_CHANGED' | 'SIGNATURE_INVALID' | 'SIGNATURE_WRONG_SIGNER' | 'SIGNATURE_WRONG_DEAL' | 'SIGNATURE_EXPIRED' | 'SIGNATURE_OUT_OF_ORDER' | 'NONCE_INVALID'
  | 'FUNDING_REQUIRED' | 'RISK_BLOCKED' | 'SETTLEMENT_NOT_ALLOWED' | 'SETTLEMENT_ALREADY_EXECUTED' | 'SETTLEMENT_FAILED' | 'ADAPTER_UNAVAILABLE' | 'FORBIDDEN' | 'VERSION_CONFLICT' | 'WALLET_INVALID' | 'TWO_FACTOR_REQUIRED' | 'RATE_LIMITED' | 'NOT_ELIGIBLE';

export class DomainError extends Error {
  constructor(public readonly code: ErrorCode, message: string, public readonly details?: Record<string, unknown>) { super(message); this.name = 'DomainError'; }
}
export const HTTP_STATUS: Record<ErrorCode, number> = {
  ILLEGAL_TRANSITION: 409, DEAL_NOT_FOUND: 404, DEAL_EXPIRED: 410, DEAL_TERMINAL: 409, INVALID_INPUT: 400, NOT_PARTICIPANT: 403,
  ASSET_NOT_CANONICAL: 422, ASSET_VERIFICATION_FAILED: 422, PRICE_UNAVAILABLE: 503, PRICE_ANOMALY: 422, LIQUIDITY_INSUFFICIENT: 422, LIQUIDITY_UNAVAILABLE: 503,
  ROUTE_NOT_VIABLE: 422, ROUTE_CHANGED: 409, SIGNATURE_INVALID: 400, SIGNATURE_WRONG_SIGNER: 403, SIGNATURE_WRONG_DEAL: 400, SIGNATURE_EXPIRED: 410, SIGNATURE_OUT_OF_ORDER: 409, NONCE_INVALID: 400,
  FUNDING_REQUIRED: 409, RISK_BLOCKED: 423, SETTLEMENT_NOT_ALLOWED: 409, SETTLEMENT_ALREADY_EXECUTED: 409, SETTLEMENT_FAILED: 500, ADAPTER_UNAVAILABLE: 503, FORBIDDEN: 403, VERSION_CONFLICT: 409, WALLET_INVALID: 400, TWO_FACTOR_REQUIRED: 428, RATE_LIMITED: 429, NOT_ELIGIBLE: 403
};
